# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2b6cb4a73ffff35af54de0d29d228453f27d42f3f0b3362780c3c1bee6ff5fe085fc0fe09290aa3e812cd2a109dea1ba7b5fc70064da64bf35b182d68f5503c

test:
  secret_key_base: fac1b100ae0cc6b15d2553da5d993fef51ab58036c4514e4c1f47b9fb1c8a6e29b4de618bc37b108cb4df1cf895f3b137075c086f0963081f1b9ea38650e09b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
